# Form implementation generated from reading ui file './src/ui/MultiPlot.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 667)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container1 = QtWidgets.QFrame(parent=Form)
        self.container1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.container1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.container1.setObjectName("container1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotA = PlotWidget(parent=self.container1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotA.sizePolicy().hasHeightForWidth())
        self.plotA.setSizePolicy(sizePolicy)
        self.plotA.setAutoFillBackground(False)
        self.plotA.setStyleSheet("background-color: #8F8;\n"
"border: 1px solid #444;")
        self.plotA.setObjectName("plotA")
        self.horizontalLayout.addWidget(self.plotA)
        self.plotB = PlotWidget(parent=self.container1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotB.sizePolicy().hasHeightForWidth())
        self.plotB.setSizePolicy(sizePolicy)
        self.plotB.setAutoFillBackground(False)
        self.plotB.setStyleSheet("background-color: #8F8;\n"
"border: 1px solid #444;")
        self.plotB.setObjectName("plotB")
        self.horizontalLayout.addWidget(self.plotB)
        self.verticalLayout.addWidget(self.container1)
        self.container2 = QtWidgets.QFrame(parent=Form)
        self.container2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.container2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.container2.setObjectName("container2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.container2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotC = PlotWidget(parent=self.container2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotC.sizePolicy().hasHeightForWidth())
        self.plotC.setSizePolicy(sizePolicy)
        self.plotC.setAutoFillBackground(False)
        self.plotC.setStyleSheet("background-color: #8F8;\n"
"border: 1px solid #444;")
        self.plotC.setObjectName("plotC")
        self.horizontalLayout_2.addWidget(self.plotC)
        self.plotD = PlotWidget(parent=self.container2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotD.sizePolicy().hasHeightForWidth())
        self.plotD.setSizePolicy(sizePolicy)
        self.plotD.setAutoFillBackground(False)
        self.plotD.setStyleSheet("background-color: #8F8;\n"
"border: 1px solid #444;")
        self.plotD.setObjectName("plotD")
        self.horizontalLayout_2.addWidget(self.plotD)
        self.verticalLayout.addWidget(self.container2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
