# Form implementation generated from reading ui file './src/ui/StartSplash.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setMaximumSize(QtCore.QSize(500, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(52)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_manualTest = QtWidgets.QPushButton(parent=Form)
        self.btn_manualTest.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_manualTest.setObjectName("btn_manualTest")
        self.verticalLayout.addWidget(self.btn_manualTest)
        self.btn_runTestProgram = QtWidgets.QPushButton(parent=Form)
        self.btn_runTestProgram.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_runTestProgram.setObjectName("btn_runTestProgram")
        self.verticalLayout.addWidget(self.btn_runTestProgram)
        self.btn_sensorCalibration = QtWidgets.QPushButton(parent=Form)
        self.btn_sensorCalibration.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_sensorCalibration.setObjectName("btn_sensorCalibration")
        self.verticalLayout.addWidget(self.btn_sensorCalibration)
        self.btn_Quit = QtWidgets.QPushButton(parent=Form)
        self.btn_Quit.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_Quit.setObjectName("btn_Quit")
        self.verticalLayout.addWidget(self.btn_Quit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Thrust Test Bench"))
        self.label_2.setText(_translate("Form", "Barnabás Kiss at Oakland University"))
        self.btn_manualTest.setText(_translate("Form", "Run Manual Test"))
        self.btn_runTestProgram.setText(_translate("Form", "Run Automated Test Program"))
        self.btn_sensorCalibration.setText(_translate("Form", "Load Cell Sensor Calibration"))
        self.btn_Quit.setText(_translate("Form", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
