# Form implementation generated from reading ui file './src/ui/TorqueMassPane.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1025, 287)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnZeroTorque = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZeroTorque.sizePolicy().hasHeightForWidth())
        self.btnZeroTorque.setSizePolicy(sizePolicy)
        self.btnZeroTorque.setObjectName("btnZeroTorque")
        self.horizontalLayout.addWidget(self.btnZeroTorque)
        self.btnProcedure = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProcedure.sizePolicy().hasHeightForWidth())
        self.btnProcedure.setSizePolicy(sizePolicy)
        self.btnProcedure.setObjectName("btnProcedure")
        self.horizontalLayout.addWidget(self.btnProcedure)
        self.btnReturn = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReturn.sizePolicy().hasHeightForWidth())
        self.btnReturn.setSizePolicy(sizePolicy)
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout.addWidget(self.btnReturn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnZeroTorque.setText(_translate("Form", "Set Zero Torque Point"))
        self.btnProcedure.setText(_translate("Form", "Begin Torque Mass Calibration Procedure"))
        self.btnReturn.setText(_translate("Form", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
